- hosts: all
  tasks:
  - name: install build requirements
    apt:
      name: ['python3-pip', 'python3-socks', 'git']
      state: present
      update_cache: yes
    become: true

  - name: apt install docker requirements
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
      state: present
    become: true

  - name: add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true

  - name: add docker apt repository
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
      state: present
    become: true

  - name: apt install docker-ce
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      state: present
      update_cache: yes
    become: true

  - name: get docker-compose
    get_url:
      url: 'https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}'
      dest: /usr/local/bin/docker-compose
      mode: '0755'
    become: true

  - name: pip install docker and boto3
    pip:
      name: ['boto3', 'docker', 'docker-compose']
      executable: pip3

  - name: create docker config directory
    file:
      path: /etc/docker
      state: directory
    become: true

  - name: copy docker daemon.json
    copy:
      content: |
        {
            "group": "docker",
            "log-driver": "journald",
            "experimental": true,
            "insecure-registries" : [],
            "features": { "buildkit": true }
        }
      dest: /etc/docker/daemon.json
    become: true

  - name: enable docker service
    service:
      name: docker
      enabled: yes
    become: true

  - name: add vagrant user to docker group
    user:
      name: vagrant
      groups: docker
      append: yes
    become: true
